# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bluefin-nvidia-580
# description will be included in the image's metadata
description: A Bluefin derived image with NVIDIA Driver 580.xx included

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: akmods
    base: main
    nvidia-driver: nvidia

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
